//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[[&quot;הוגן&quot;,&quot;fair&quot;,,,0],[,,,&quot;fe(?)r&quot;]],[[&quot;adjective&quot;,[&quot;הוֹגֶן&quot;,&quot;בֵּינוֹנִי&quot;,&quot;בָּהִיר&quot;,&quot;יָפֶה&quot;,&quot;טוֹב&quot;,&quot;טוֹב לְמַדַי&quot;,&quot;נוֹחַ&quot;,&quot;כָּשֵׁר&quot;],[[&quot;הוֹגֶן&quot;,[&quot;fair&quot;,&quot;decent&quot;,&quot;straight&quot;,&quot;upright&quot;,&quot;reasonable&quot;,&quot;suitable&quot;],,0.46759713],[&quot;בֵּינוֹנִי&quot;,[&quot;medium&quot;,&quot;moderate&quot;,&quot;mediocre&quot;,&quot;fair&quot;,&quot;middle&quot;,&quot;mid&quot;],,0.058019698],[&quot;בָּהִיר&quot;,[&quot;bright&quot;,&quot;clear&quot;,&quot;light&quot;,&quot;fair&quot;,&quot;sunny&quot;,&quot;lucid&quot;],,0.0069519016],[&quot;יָפֶה&quot;,[&quot;beautiful&quot;,&quot;pretty&quot;,&quot;nice&quot;,&quot;lovely&quot;,&quot;well&quot;,&quot;fair&quot;]],[&quot;טוֹב&quot;,[&quot;good&quot;,&quot;well&quot;,&quot;kind&quot;,&quot;fair&quot;]],[&quot;טוֹב לְמַדַי&quot;,[&quot;fair&quot;]],[&quot;נוֹ [rest of string was truncated]&qu....
        /// </summary>
        internal static string fairTranslation {
            get {
                return ResourceManager.GetString("fairTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfLanguage xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Language&gt;
        ///    &lt;Symbol&gt;af&lt;/Symbol&gt;
        ///    &lt;NativeName&gt;Afrikaans&lt;/NativeName&gt;
        ///    &lt;EnglishName&gt;Afrikaans&lt;/EnglishName&gt;
        ///	&lt;IsRightToLeft&gt;false&lt;/IsRightToLeft&gt;  
        ///&lt;/Language&gt;  
        ///  &lt;Language&gt;
        ///    &lt;Symbol&gt;sq&lt;/Symbol&gt;
        ///    &lt;NativeName&gt;shqipe&lt;/NativeName&gt;
        ///    &lt;EnglishName&gt;Albanian&lt;/EnglishName&gt;
        ///  &lt;IsRightToLeft&gt;false&lt;/IsRightToLeft&gt; 
        ///&lt;/Language&gt;  
        ///&lt;Language&gt;  
        ///    &lt;Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[[&quot;שָׂפָה&quot;,&quot;language&quot;,,,2],[,,,&quot;?laNGgwij&quot;]],[[&quot;noun&quot;,[&quot;שָׂפָה&quot;,&quot;לָשׁוֹן&quot;],[[&quot;שָׂפָה&quot;,[&quot;language&quot;,&quot;lip&quot;,&quot;tongue&quot;,&quot;border&quot;,&quot;edge&quot;,&quot;bordure&quot;],,0.87980551],[&quot;לָשׁוֹן&quot;,[&quot;language&quot;,&quot;tongue&quot;,&quot;speech&quot;,&quot;lingo&quot;,&quot;expression&quot;],,0.030412389]],&quot;language&quot;,1]],&quot;en&quot;,,,[[&quot;language&quot;,32000,[[&quot;שָׂפָה&quot;,1000,true,false],[&quot;לָשׁוֹן&quot;,1000,true,false],[&quot;השפה&quot;,287,true,false],[&quot;בשפה&quot;,12,true,false],[&quot;שפת&quot;,2,true,false]],[[0,8]],&quot;language&quot;,0,0]],1,,[[&quot;en&quot;],,[1],[&quot;en&quot;]],,,[[&quot;noun&quot;,[[[&quot;speech&quot;,&quot;writing&quot;,&quot;communication&quot;,&quot;conversation&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languageTranslation {
            get {
                return ResourceManager.GetString("languageTranslation", resourceCulture);
            }
        }
    }
}
